version: "3.8"

services:

  sso:
    image: sso-backend
    container_name: sso-backend
    build:
      context: .
      dockerfile: Dockerfile.sso
    ports:
      - "0.0.0.0:44044:44044"
      - "0.0.0.0:8090:8090"
    volumes:
      - ./settings:/app/settings
      - ./secrets:/app/secrets:ro 
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-commander:
        condition: service_healthy
      adminer:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    container_name: postgres_sso_go
    image: postgres:16.4
    env_file:
      - sso.env
    command: postgres -p 5555
    volumes:
      - postgres-data-sso:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5555:5555"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5555"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer     
    ports:
      - "0.0.0.0:8100:8080"  
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis_cache
    image: redis:7.4
    env_file:
      - sso.env
    volumes:
      - redis-data:/data
    ports:
      - "0.0.0.0:6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-a", "$${REDIS_PASS}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    env_file:
      - sso.env
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data-sso:

networks:
  app-network:
    driver: bridge